name: Metrics

on:
  schedule: # Schedule updates (e.g. daily)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, repositories
          plugin_activity: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
